services:
  order-service:
    build: ./backend/order-service
    container_name: order-service
    ports:
      - "8000:8000"
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - fastfood-net

  user-service:
    build: ./backend/user-service
    container_name: user-service
    ports:
      - "8001:8001"
    command: "uvicorn main:app --host 0.0.0.0 --port 8001"
    networks:
      - fastfood-net

  product-service:
    build: ./backend/product-service
    container_name: product-service
    ports:
      - "8002:8002"
    command: "uvicorn main:app --host 0.0.0.0 --port 8002"
    networks:
      - fastfood-net

  payment-service:
    build: ./backend/payment-service
    container_name: payment-service
    ports:
      - "8003:8003"
    command: "uvicorn main:app --host 0.0.0.0 --port 8003"
    networks:
      - fastfood-net

networks:
  fastfood-net:
    external: false
