version: '3.9'

services:
  order-service:
    build: ./backend/order-service
    container_name: order-service
    ports:
      - "8000:8000"

  user-service:
    build: ./backend/user-service
    container_name: user-service
    ports:
      - "8001:8001"

  product-service:
    build: ./backend/product-service
    container_name: product-service
    ports:
      - "8002:8002"

  payment-service:
    build: ./backend/payment-service
    container_name: payment-service
    ports:
      - "8003:8003"
