version: "3.8"

services:
  user-service:
    build: ./backend/user-service
    container_name: user-service
    ports:
      - "8004:8000"
    volumes:
      - ./backend/user-service/db:/app/db
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"

  product-service:
    build: ./backend/product-service
    container_name: product-service
    ports:
      - "8002:8002"
    volumes:
      - ./backend/product-service/db:/app/db
    command: "uvicorn main:app --host 0.0.0.0 --port 8002"

  order-service:
    build: ./backend/order-service
    container_name: order-service
    ports:
      - "8000:8000"
    volumes:
      - ./backend/order-service/db:/app/db
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"

  payment-service:
    build: ./backend/payment-service
    container_name: payment-service
    ports:
      - "8003:8003"
    volumes:
      - ./backend/payment-service/db:/app/db
    command: "uvicorn main:app --host 0.0.0.0 --port 8003"
