global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8002']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8003']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8000']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8001']
