global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['cadvisor:8080']

  # Theo dõi các service chính (nếu có metrics endpoint)
  - job_name: 'fastfood-services'
    metrics_path: /metrics
    static_configs:
      - targets: [
          'order-service:8001',
          'payment-service:8002',
          'product-service:8003',
          'user-service:8004'
        ]
