global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8000']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8001']
